on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: CI

jobs:
  ci-rust-test:
    name: Rust tests - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      RUST_CHANNEL: "stable"

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install libxcb-composite0-dev
    
    - name: Install Rust toolchain
      run: |
        rustup update --no-self-update ${{ env.RUST_CHANNEL }}
        rustup component add --toolchain ${{ env.RUST_CHANNEL }} rustfmt rust-src
        rustup default ${{ env.RUST_CHANNEL }}
    - name: Rust Test All Features
      run: cargo test --all-features
    - name: Rust Fmt check
      run: cargo fmt --all -- --check
    - name: Rust Clippy Check
      run: cargo clippy --workspace --all-targets --all-features --  -D warnings -W clippy::all
